class BasicModelRunner:
    def __init__(self, model_name):
        if model_name == "meta-llama/Llama-2-7b-hf":
            self.responses = {
                "Tell me how to train my dog to sit": "Tell me how to train my dog to stay.\nTell me how to teach my dog to come.\nTell me how to get my dog to heel.\nTell me how to stop my dog from jumping.\nTell me how to make my dog stop barking.\nTell me how I can get my dog to stop chewing.\nTell me how to house train my dog.\nTell me how to potty train my dog.\nTell me how to train my dog to walk on a leash.\nTell me how to crate train my dog.\nTell Me How To Train My Dog To Sit, Stay, Come, Heel, Stop Jumping, Stop Barking, Stop Chewing, House Train, Potty Train, Walk On A Leash, Crate Train, And More!\nTell Me How To Train Your Dog To Sit, Stay, Heel, Come, Stop Jumping, Stop Chewing, House Trained, Potty Trained, Walk On A Leash, And More!\nTell me how to train your dog to sit.\nTell Me How To House Train My Dog.",
                "[INST]Tell me how to train my dog to sit[/INST]": "[INST]Tell me how to train my dog to sit[/INST]",
                "What do you think of Mars?": "I think it's a great planet.\nI think it's a good planet.\nI think it'll be a great planet.\nI think we should go there.\nI think we should go back there.\nI think we should stay there.\nI think we should leave there.\nI think we should colonize there.\nI think we should terraform there.\nI think we should mine there.\nI think we should build there.\nI think we should live there.\nI think we should die there.\nI think we should be there.\nI think we should have been there.\nI think we should never be there.\nI think we'll be there.\nI think we won't be there.\nI think we will be there.\nI think we can be there.\nI think we could be there.\nI think we would be there.\nI think we might be there.\nI think we may be there.\nI think we shall be there.\nI think we must be there.\nI think we have to be there.\nI think we need to be there.\nI think I'll be there.\nI know I'll be there.",
                "taylor swift's best friend": "I'm not sure if I've mentioned this before, but I'm a huge Taylor Swift fan.\nI've been a fan since her first album, and I've been a fan ever since. I've been a fan of her music, her style, her personality, and her music. I've been a fan for a long time.\nI've been a fan of Taylor Swift for a long time. I've been a fan of her music for a long time. I'm a fan of her style, her personality, her music, and her music. I've been a fan for a long, long time.\nI've always been a fan of Taylor Swift. I've always been a fan of her music.\nI've always been a big fan of her style. I've always been a huge fan of her personality. I've always been a massive fan of her music. I'm a fan of Taylor Swift. I love her music. I love her style. I love her personality. I love her music. I'm a huge fan of Taylor Swift.\nI've always been an avid fan of Taylor Swift. I'm",
                "Agent: I'm here to help you with your Amazon deliver order.\nCustomer: I didn't get my item\nAgent: I'm sorry to hear that. Which item was it?\nCustomer: the blanket\nAgent:": "I'm sorry to hear that but I'm here to help.\nCustomer: I don't get the blanket\nCustomer: I don't have the blanket\nAgent: I don't understand.\nAgent: I'm sorry. I don't understand. customer: I don't have the blanket Agent: I'm so sorry to hear that.\nCustomer: I don t have the blanket\nAgent: Oh no, I'm so sorry to hear about that.\ncustomer: I",
            }
        elif model_name == "meta-llama/Llama-2-7b-chat-hf":
            self.responses = {
                "Tell me how to train my dog to sit": "on command. Training your dog to sit is a basic obedience command that can be achieved with patience, consistency, and positive reinforcement. Here's a step-by-step guide on how to train your dog to sit:\n\n1. Choose a quiet and distraction-free area: Find a quiet room or area where your dog can focus on you without getting distracted.\n2. Have treats ready: Choose your dog's favorite treats and have them readily available to reward good behavior.\n3. Stand in front of your dog: Stand in front of your dog and hold a treat close to their nose.\n4. Move the treat up and back: Slowly move the treat upwards and backwards, towards your dog's tail, while saying \"sit\" in a calm and clear voice.\n5. Dog will follow the treat: As you move the treat, your dog should naturally sit down to follow it. The moment they touch their bottom to the ground, give them the treat and praise them.",
                "[INST]Tell me how to train my dog to sit[/INST]": 'Training your dog to sit is a basic obedience command that can be achieved with patience, consistency, and positive reinforcement. Here\'s a step-by-step guide on how to train your dog to sit:\n\n1. Choose a quiet and distraction-free area: Find a quiet room or area where your dog can focus on you without getting distracted.\n2. Have treats ready: Choose your dog\'s favorite treats and have them readily available to reward good behavior.\n3. Stand in front of your dog: Stand in front of your dog and hold a treat close to their nose.\n4. Move the treat up and back: Slowly move the treat upwards and backwards, towards your dog\'s tail, while saying "sit" in a calm and clear voice.\n5. Dog will follow the treat: As you move the treat, your dog should naturally sit down to follow it. The moment they touch their bottom to the ground, give them the treat and praise them.\n6. Repeat the process: Repeat steps 3-5 several times, so your dog learns to associate the command "sit" with the action of sitting down.',
                "What do you think of Mars?": "Mars is a fascinating planet that has captured the imagination of humans for centuries. It is the fourth planet from the Sun in our solar system and is kn own for its reddish appearance. Mars is a rocky planet with a thin atmosphere, and its surface is characterized by volcanoes, canyons, and impact crater.\nOne of the most intriguing aspects of Mars is its potential for supporting life. While there is currently no evidence of life on Mars, the planet's atmosphere and geology suggest that it may have been habitable in the past. NASA's Curiosity rover has been exploring Mars since 2012, and has discovered evidence of water on the planet, which is a key ingredient for life.\nMars is also a popular target for space missions and future human settlements. Several space agencies and private companies are planning missions to Mars in the coming years, with the goal of establishing a human presence on the pl anet. The challenges of establishing a human settlement on Mars are significa nt, including the harsh environment, lack of resources, and distance from Earth. However, many experts believe that Mars is the next logical step in the expl",
                "taylor swift's best friend": "Taylor Swift's best friend is a person who has been by her side through thick and thin. Here are some possible candidates:\n1. Abigail Anderson - Abigail is Taylor's childhood friend and has been a constant presence in her life. The two have been inseparable since they met in kindergarten and have shared countless memories together.\n2. Selena Gomez - Selena and Taylor have been friends for over a decade and have been through a lot together. They have collaborated on music projects, gone on vacation together, and have been there for each other through personal struggles.\n3. Liz Rose - Liz is a songwriter and producer who has worked with Taylor on many of her hit songs. The two have a close creative partnership and have been friends for many years.\n4. Joe Jonas - Joe and Taylor were friends for several years before they started dating in 2008. They have been on-again, off-again since then and have been there for each other during some of the most significant moments in each other's lives.\n5. Ed Sheeran - Ed and Taylor have been friends",
                "Agent: I'm here to help you with your Amazon deliver order.\nCustomer: I didn't get my item\nAgent: I'm sorry to hear that. Which item was it?\nCustomer: the blanket\nAgent:": "I see. Can you please provide me with your order number so I can look into this for you?\nCustomer: I don't have the order number.\nAgent: Okay, no worries. Can you please tell me the name of the item you didn't receive?\nCustomer: Blanket\nAgent: And what was the shipping address for this item?\nCustomer: 123 Main St\nAgent: Okay, thank you. I'm going to check on the status of your order. Can you please hold for just a moment?\nCustomer: (hangs up)\nThis is a common scenario in customer service, where the agent is trying to gather information from the customer to help resolve their issue. The agent is using active listening skills to gather information from the customer, such as the order number, the name of the item, and the shipping address. The agent is also using empathy to acknowledge the customer's concern and let them know that they are there to help.",
            }
        else:
            raise ValueError("Invalid model. Please stick to the notebook example.")

    def __call__(self, prompt):
        return self.responses.get(
            prompt,
            "Sorry, I don't know how to respond to that. Please stick to the notebook example.",
        )
